{% set name = "chainlit" %}
{% set version = "2.6.7" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Chainlit/chainlit/archive/refs/tags/{{ version }}.tar.gz
  sha256: c7e07bb7a7098e38f9e11585da6784be374b698102d2ea32e626de3b1848b892

build:
  entry_points:
    - chainlit = chainlit.cli:cli
  noarch: python
  script:
    - cd backend
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - pnpm
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - httpx >=0.23.0
    - literalai 0.1.201
    - dataclasses-json >=0.6.7,<0.7.0
    - fastapi >=0.116.1,<0.117
    - starlette >=0.47.2
    - uvicorn >=0.35.0
    - python-socketio >=5.11.0,<6.0.0
    - aiofiles >=23.1.0,<25.0.0
    - syncer >=2.0.3,<3.0.0
    - asyncer >=0.0.8,<0.0.9
    - mcp >=1.11.0,<2
    - nest-asyncio >=1.6.0,<2.0.0
    - click >=8.1.3,<9.0.0
    - tomli >=2.0.1,<3.0.0
    - pydantic >=2.7.2,<3
    - python-dotenv >=1.0.0,<2.0.0
    - uptrace >=1.29.0,<2.0.0
    - watchfiles >=0.20.0,<0.21.0
    - filetype >=1.2.0,<2.0.0
    - lazify >=0.4.0,<0.5.0
    - packaging >=23.1
    - python-multipart >=0.0.18,<0.0.19
    - pyjwt >=2.8.0,<3.0.0

test:
  imports:
    - chainlit
  commands:
    - pip check
    - chainlit --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://chainlit.io/
  summary: Build Conversational AI.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - timkpaine
